Add max_surge value to node pool
FairwindsOps/azure-terraform-modules pull request #25
Opened 2021-08-24 15:14 UTC by katiekeel

2021-08-24 15:16 UTC, sudermanjr requested changes
You'll have to add this variable definition to the variables.tf, along with a description and preferably a default in order to be backward compatible

2021-08-24 15:22 UTC, katiekeel commented on aks_node_pool/variables.tf
> +  type        = string
As best I can tell, [this should be a string](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster_node_pool#max_surge). I don't see anything in the Terraform types about percentages being their own thing.

2021-08-24 15:54 UTC, katiekeel commented
Ok - here's what the plan output says. It looks like the `max_surge` setting just... didn't exist before? Also, unclear whether its parent `upgrade_settings` block applies to node images upgrades, or just K8s version upgrades.

![Screen Shot 2021-08-24 at 11 53 26 AM](https://user-images.githubusercontent.com/11282627/130649358-4dea448a-07ed-4d8b-b2a7-a82631f8b379.png)

2021-08-24 16:00 UTC, katiekeel commented
I checked the docs [here](https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#customize-node-surge-upgrade) and they recommend the `max_surge` be capped at `33%` for prod environments, so I went a bit more conservative and set it to `25%`.

Also, it does explicitly say that `max_surge` [applies to node image upgrades.](https://docs.microsoft.com/en-us/azure/aks/node-image-upgrade#upgrade-node-images-with-node-surge)

2021-09-20 19:28 UTC, lucasreed approved these changes

2021-09-20 19:31 UTC, sudermanjr approved these changes

2021-09-27 13:38 UTC, katiekeel commented
/cla /license /how-does-this-work

2021-09-27 14:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FairwindsOps/azure-terraform-modules?pullRequest=25) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FairwindsOps/azure-terraform-modules?pullRequest=25) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FairwindsOps/azure-terraform-modules?pullRequest=25) it.</sub>

2021-09-27 14:23 UTC, merged